name: Docker CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Build Docker image
      run: docker build -t 980029202902902/nestjs-deploy:${{ github.sha }} .
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker image
      run: docker push 980029202902902/nestjs-deploy:${{ github.sha }}
    - name: docker compose run
      run: docker compose up -d
